In [1]:
import pandas as pd
from pathlib import Path

MAIN_PATH = Path("../data/processed/main_df.csv")
ORDER_ITEMS_AND_PRODUCTS_PATH = Path("../data/processed/order_items_and_products_df.csv")

order_items_and_products_df = pd.read_csv(ORDER_ITEMS_AND_PRODUCTS_PATH)

In [2]:
# order items and products df
order_items_and_products_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,Cool Stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,Pet Shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,Moveis Decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,Perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,Ferramentas Jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0

In [ ]:
# total spend
order_items_and_products_df["total_spend"] = order_items_and_products_df.price + order_items_and_products_df.freight_value

In [4]:
# price bins
order_items_and_products_df.price.value_counts(bins=5)
price_labels = ["Low", "Medium", "High"]
price_bins = [0, 50, 500, 10000]

order_items_and_products_df["price_category"] = pd.cut(order_items_and_products_df.price, bins=price_bins, labels=price_labels)

In [5]:
# volume 
order_items_and_products_df["volume"] = order_items_and_products_df.product_length_cm * order_items_and_products_df.product_height_cm * order_items_and_products_df.product_width_cm

In [6]:
# density
order_items_and_products_df["density"] = (order_items_and_products_df.product_weight_g / order_items_and_products_df.volume).astype(float).round(2)

In [7]:
# freight per price ratio
order_items_and_products_df["freight_per_price"] = (order_items_and_products_df.freight_value / order_items_and_products_df.price).astype(float).round(2)

In [8]:
# final dataframe
order_items_and_products_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,total_spend,price_category,volume,density,freight_per_price
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,Cool Stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0,72.19,Medium,3528.0,0.18,0.23
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,Pet Shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0,259.83,Medium,60000.0,0.50,0.08
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,Moveis Decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0,216.87,Medium,14157.0,0.22,0.09
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,Perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0,25.78,Low,2400.0,0.08,0.98
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,Ferramentas Jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0,218.04,Medium,42000.0,0.09,0.09

In [9]:
# save feature engineered dataset
order_items_and_products_df.to_csv("../data/processed/order_items_and_products_feature_engineered_df.csv", index=False)