In [312]:
import pandas as pd
from pathlib import Path
import numpy as np

CHICAGO_CENSUS_PATH = Path("../data/raw/ChicagoCensusData.csv")
CHICAGO_CRIME_PATH = Path("../data/raw/ChicagoCrimeData.csv")
CHICAGO_PUBLIC_SCHOOLS_PATH = Path("../data/raw/ChicagoPublicSchools.csv")

chicago_census_df = pd.read_csv(CHICAGO_CENSUS_PATH)
chicago_crime_df = pd.read_csv(CHICAGO_CRIME_PATH)
chicago_public_schools_df = pd.read_csv(CHICAGO_PUBLIC_SCHOOLS_PATH)

# Chicago Census Dataframe

In [313]:
# look at chicago census df
chicago_census_df.head()

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0

In [314]:
# shape
chicago_census_df.shape

(78, 9)

In [315]:
# info
chicago_census_df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   COMMUNITY_AREA_NUMBER                         77 non-null     float64
 1   COMMUNITY_AREA_NAME                           78 non-null     str
 2   PERCENT_OF_HOUSING_CROWDED                    78 non-null     float64
 3   PERCENT_HOUSEHOLDS_BELOW_POVERTY              78 non-null     float64
 4   PERCENT_AGED_16__UNEMPLOYED                   78 non-null     float64
 5   PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA  78 non-null     float64
 6   PERCENT_AGED_UNDER_18_OR_OVER_64              78 non-null     float64
 7   PER_CAPITA_INCOME                             78 non-null     int64
 8   HARDSHIP_INDEX                                77 non-null     float64
dtypes: float64(7), int64(1), str(1)
memory usage: 6.5 KB

In [316]:
# check duplicates
chicago_census_df.duplicated().sum()

np.int64(0)

In [317]:
# NaN values
chicago_census_df.isna().sum()

COMMUNITY_AREA_NUMBER                           1
COMMUNITY_AREA_NAME                             0
PERCENT_OF_HOUSING_CROWDED                      0
PERCENT_HOUSEHOLDS_BELOW_POVERTY                0
PERCENT_AGED_16__UNEMPLOYED                     0
PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA    0
PERCENT_AGED_UNDER_18_OR_OVER_64                0
PER_CAPITA_INCOME                               0
HARDSHIP_INDEX                                  1
dtype: int64

In [318]:
# look at the missing values
chicago_census_df.loc[chicago_census_df.COMMUNITY_AREA_NUMBER.isna()]

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
77,NaN,CHICAGO,4.7,19.7,12.9,19.5,33.5,28202,NaN

In [319]:
# since it is only a row (which is also the primary key to join tables), we can drop it
missing_com_area = chicago_census_df.loc[chicago_census_df.COMMUNITY_AREA_NUMBER.isna()].index
chicago_census_df.drop(index=missing_com_area, inplace=True)

In [320]:
# check missing values now
chicago_census_df.isna().sum()

COMMUNITY_AREA_NUMBER                           0
COMMUNITY_AREA_NAME                             0
PERCENT_OF_HOUSING_CROWDED                      0
PERCENT_HOUSEHOLDS_BELOW_POVERTY                0
PERCENT_AGED_16__UNEMPLOYED                     0
PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA    0
PERCENT_AGED_UNDER_18_OR_OVER_64                0
PER_CAPITA_INCOME                               0
HARDSHIP_INDEX                                  0
dtype: int64

In [321]:
# are there unusual categories?
chicago_census_df.COMMUNITY_AREA_NAME.unique()

<ArrowStringArray>
[           'Rogers Park',             'West Ridge',                 'Uptown',
         'Lincoln Square',           'North Center',              'Lake View',
           'Lincoln Park',        'Near North Side',            'Edison Park',
           'Norwood Park',         'Jefferson Park',            'Forest Glen',
             'North Park',            'Albany Park',           'Portage Park',
            'Irving Park',                'Dunning',             'Montclaire',
         'Belmont Cragin',                'Hermosa',               'Avondale',
           'Logan Square',          'Humboldt park',              'West Town',
                 'Austin',     'West Garfield Park',     'East Garfield Park',
         'Near West Side',         'North Lawndale',         'South Lawndale',
        'Lower West Side',                   'Loop',        'Near South Side',
          'Armour Square',                'Douglas',                'Oakland',
            'Fuller Park',        'Grand Boulevard',                'Kenwood',
        'Washington Park',              'Hyde Park',               'Woodlawn',
            'South Shore',                'Chatham',            'Avalon Park',
          'South Chicago',               'Burnside',        'Calumet Heights',
               'Roseland',                'Pullman',          'South Deering',
              'East Side',           'West Pullman',              'Riverdale',
              'Hegewisch',         'Garfield Ridge',         'Archer Heights',
          'Brighton Park',          'McKinley Park',             'Bridgeport',
               'New City',            'West Elsdon',              'Gage Park',
               'Clearing',              'West Lawn',           'Chicago Lawn',
         'West Englewood',              'Englewood', 'Greater Grand Crossing',
                'Ashburn',         'Auburn Gresham',                'Beverly',
      'Washington Height',        'Mount Greenwood',            'Morgan Park',
                 'O'Hare',              'Edgewater']
Length: 77, dtype: str

In [322]:
# change COMMUNITY AREA NAME to category
chicago_census_df.COMMUNITY_AREA_NAME = chicago_census_df.COMMUNITY_AREA_NAME.astype("category")

# Chicago Public Schools Dataframe

In [323]:
# look at the df
chicago_public_schools_df.head()

,School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,...,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NDA,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"(41.92449696, -87.64452163)"
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"(41.76032435, -87.55673627)"
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,http://schoolreports.cps.edu/SchoolProgressRep...,Midway Elementary Network,...,NDA,1148427.165,1851012.215,41.747111,-87.731702,70,ASHBURN,13,8,"(41.74711093, -87.73170248)"
3,609993,Agustin Lara Elementary Academy,ES,4619 S Wolcott Ave,Chicago,IL,60609,(773) 535-4389,http://schoolreports.cps.edu/SchoolProgressRep...,Pershing Elementary Network,...,NDA,1164504.290,1873959.199,41.809757,-87.672145,61,NEW CITY,20,9,"(41.8097569, -87.6721446)"
4,610513,Air Force Academy High School,HS,3630 S Wells St,Chicago,IL,60609,(773) 535-1590,http://schoolreports.cps.edu/SchoolProgressRep...,Southwest Side High School Network,...,91.8,1175177.622,1880745.126,41.828146,-87.632794,34,ARMOUR SQUARE,11,9,"(41.82814609, -87.63279369)"

In [324]:
# shape
chicago_public_schools_df.shape

(566, 78)

In [325]:
# info
chicago_public_schools_df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 78 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   School_ID                                         566 non-null    int64
 1   NAME_OF_SCHOOL                                    566 non-null    str
 2   Elementary, Middle, or High School                566 non-null    str
 3   Street_Address                                    566 non-null    str
 4   City                                              566 non-null    str
 5   State                                             566 non-null    str
 6   ZIP_Code                                          566 non-null    int64
 7   Phone_Number                                      566 non-null    str
 8   Link                                              565 non-null    str
 9   Network_Manager                                   566 non-null    str
 10  Collaborative_Name                                566 non-null    str
 11  Adequate_Yearly_Progress_Made_                    566 non-null    str
 12  Track_Schedule                                    566 non-null    str
 13  CPS_Performance_Policy_Status                     566 non-null    str
 14  CPS_Performance_Policy_Level                      566 non-null    str
 15  HEALTHY_SCHOOL_CERTIFIED                          566 non-null    str
 16  Safety_Icon                                       566 non-null    str
 17  SAFETY_SCORE                                      513 non-null    float64
 18  Family_Involvement_Icon                           566 non-null    str
 19  Family_Involvement_Score                          566 non-null    str
 20  Environment_Icon                                  566 non-null    str
 21  Environment_Score                                 513 non-null    float64
 22  Instruction_Icon                                  566 non-null    str
 23  Instruction_Score                                 513 non-null    float64
 24  Leaders_Icon                                      566 non-null    str
 25  Leaders_Score                                     566 non-null    str
 26  Teachers_Icon                                     566 non-null    str
 27  Teachers_Score                                    566 non-null    str
 28  Parent_Engagement_Icon                            566 non-null    str
 29  Parent_Engagement_Score                           566 non-null    str
 30  Parent_Environment_Icon                           566 non-null    str
 31  Parent_Environment_Score                          566 non-null    str
 32  AVERAGE_STUDENT_ATTENDANCE                        565 non-null    str
 33  Rate_of_Misconducts__per_100_students_            566 non-null    float64
 34  Average_Teacher_Attendance                        566 non-null    str
 35  Individualized_Education_Program_Compliance_Rate  566 non-null    str
 36  Pk_2_Literacy__                                   566 non-null    str
 37  Pk_2_Math__                                       566 non-null    str
 38  Gr3_5_Grade_Level_Math__                          566 non-null    str
 39  Gr3_5_Grade_Level_Read__                          566 non-null    str
 40  Gr3_5_Keep_Pace_Read__                            566 non-null    str
 41  Gr3_5_Keep_Pace_Math__                            566 non-null    str
 42  Gr6_8_Grade_Level_Math__                          566 non-null    str
 43  Gr6_8_Grade_Level_Read__                          566 non-null    str
 44  Gr6_8_Keep_Pace_Math_                             566 non-null    str
 45  Gr6_8_Keep_Pace_Read__                            566 non-null    str
 46  Gr_8_Explore_Math__                               566 non-null    str
 47  Gr_8_Explore_Read__                               566 non-null    str
 48  ISAT_Exceeding_Math__                             476 non-null    float64
 49  ISAT_Exceeding_Reading__                          476 non-null    float64
 50  ISAT_Value_Add_Math                               468 non-null    float64
 51  ISAT_Value_Add_Read                               468 non-null    float64
 52  ISAT_Value_Add_Color_Math                         566 non-null    str
 53  ISAT_Value_Add_Color_Read                         566 non-null    str
 54  Students_Taking__Algebra__                        566 non-null    str
 55  Students_Passing__Algebra__                       566 non-null    str
 56  9th Grade EXPLORE (2009)                          566 non-null    str
 57  9th Grade EXPLORE (2010)                          566 non-null    str
 58  10th Grade PLAN (2009)                            566 non-null    str
 59  10th Grade PLAN (2010)                            566 non-null    str
 60  Net_Change_EXPLORE_and_PLAN                       566 non-null    str
 61  11th Grade Average ACT (2011)                     566 non-null    str
 62  Net_Change_PLAN_and_ACT                           566 non-null    str
 63  College_Eligibility__                             566 non-null    str
 64  Graduation_Rate__                                 566 non-null    str
 65  College_Enrollment_Rate__                         566 non-null    str
 66  COLLEGE_ENROLLMENT                                566 non-null    int64
 67  General_Services_Route                            566 non-null    int64
 68  Freshman_on_Track_Rate__                          566 non-null    str
 69  X_COORDINATE                                      566 non-null    float64
 70  Y_COORDINATE                                      566 non-null    float64
 71  Latitude                                          566 non-null    float64
 72  Longitude                                         566 non-null    float64
 73  COMMUNITY_AREA_NUMBER                             566 non-null    int64
 74  COMMUNITY_AREA_NAME                               566 non-null    str
 75  Ward                                              566 non-null    int64
 76  Police_District                                   566 non-null    int64
 77  Location                                          566 non-null    str
dtypes: float64(12), int64(7), str(59)
memory usage: 593.2 KB

In [326]:
# check duplicates
chicago_public_schools_df.duplicated().sum()

np.int64(0)

In [327]:
# check NaN values
chicago_public_schools_df.isna().sum().sort_values(ascending=False)

ISAT_Value_Add_Read         98
ISAT_Value_Add_Math         98
ISAT_Exceeding_Reading__    90
ISAT_Exceeding_Math__       90
Environment_Score           53
                            ..
COMMUNITY_AREA_NUMBER        0
COMMUNITY_AREA_NAME          0
Ward                         0
Police_District              0
Location                     0
Length: 78, dtype: int64

In [328]:
# replace NDA with NaN
chicago_public_schools_df.replace("NDA", np.nan, inplace=True)

,School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,...,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NaN,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"(41.92449696, -87.64452163)"
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NaN,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"(41.76032435, -87.55673627)"
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,http://schoolreports.cps.edu/SchoolProgressRep...,Midway Elementary Network,...,NaN,1148427.165,1851012.215,41.747111,-87.731702,70,ASHBURN,13,8,"(41.74711093, -87.73170248)"
3,609993,Agustin Lara Elementary Academy,ES,4619 S Wolcott Ave,Chicago,IL,60609,(773) 535-4389,http://schoolreports.cps.edu/SchoolProgressRep...,Pershing Elementary Network,...,NaN,1164504.290,1873959.199,41.809757,-87.672145,61,NEW CITY,20,9,"(41.8097569, -87.6721446)"
4,610513,Air Force Academy High School,HS,3630 S Wells St,Chicago,IL,60609,(773) 535-1590,http://schoolreports.cps.edu/SchoolProgressRep...,Southwest Side High School Network,...,91.8,1175177.622,1880745.126,41.828146,-87.632794,34,ARMOUR SQUARE,11,9,"(41.82814609, -87.63279369)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,610172,William T Sherman Elementary School,ES,1000 W 52nd St,Chicago,IL,60609,(773) 535-1757,http://schoolreports.cps.edu/SchoolProgressRep...,AUSL Schools,...,NaN,1170500.817,1870373.159,41.799788,-87.650255,61,NEW CITY,16,9,"(41.79978772, -87.65025483)"
562,609844,William W Carter Elementary School,ES,5740 S Michigan Ave,Chicago,IL,60637,(773) 535-0860,http://schoolreports.cps.edu/SchoolProgressRep...,Burnham Park Elementary Network,...,NaN,1178101.365,1866810.123,41.789841,-87.622490,40,WASHINGTON PARK,20,2,"(41.78984129, -87.62248974)"
563,610088,Wolfgang A Mozart Elementary School,ES,2200 N Hamlin Ave,Chicago,IL,60647,(773) 534-4160,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NaN,1150644.396,1914368.955,41.920927,-87.721925,22,LOGAN SQUARE,35,25,"(41.92092734, -87.72192541)"
564,609977,Woodlawn Community Elementary School,ES,6657 S Kimbark Ave,Chicago,IL,60637,(773) 535-0801,http://schoolreports.cps.edu/SchoolProgressRep...,Burnham Park Elementary Network,...,NaN,1185825.188,1860883.579,41.773400,-87.594356,42,WOODLAWN,5,3,"(41.77339962, -87.59435584)"
565,610392,World Language Academy High School,HS,3120 S Kostner Ave,Chicago,IL,60623,(773) 535-4334,http://schoolreports.cps.edu/SchoolProgressRep...,West Side High School Network,...,76,1147521.302,1883405.128,41.836020,-87.734195,30,SOUTH LAWNDALE,22,10,"(41.83601953, -87.73419465)"

In [329]:
# drop Location since we already have Latitude and Longitude
chicago_public_schools_df = chicago_public_schools_df.drop("Location", axis=1)

In [330]:
# replace % with "" in columns that contain %
perc_cols = ["AVERAGE_STUDENT_ATTENDANCE", "Average_Teacher_Attendance", "Individualized_Education_Program_Compliance_Rate"]

for perc_col in perc_cols:
    chicago_public_schools_df[perc_col] = chicago_public_schools_df[perc_col].astype("str").str.replace("%", "", regex=False)
    chicago_public_schools_df[perc_col] = chicago_public_schools_df[perc_col].astype(float)

In [331]:
# drop columns ending with _Icon as other columns contain more information
icon_cols = [c for c in chicago_public_schools_df.columns if "_Icon" in c]
chicago_public_schools_df.drop(columns=icon_cols, inplace=True)

In [332]:
# convert needed columns for clustering to numeric
num_cols = ["SAFETY_SCORE", "Family_Involvement_Score", "Environment_Score", 
            "Instruction_Score", "AVERAGE_STUDENT_ATTENDANCE"]

for num_col in num_cols:
    chicago_public_schools_df[num_col] = pd.to_numeric(chicago_public_schools_df[num_col], errors="coerce")

In [333]:
# NaN summary
chicago_public_schools_df.isna().mean().sort_values(ascending=False)

College_Enrollment_Rate__        0.863958
Graduation_Rate__                0.860424
Net_Change_PLAN_and_ACT          0.855124
10th Grade PLAN (2009)           0.855124
11th Grade Average ACT (2011)    0.853357
                                   ...
Longitude                        0.000000
COMMUNITY_AREA_NUMBER            0.000000
COMMUNITY_AREA_NAME              0.000000
Ward                             0.000000
Police_District                  0.000000
Length: 69, dtype: float64

In [334]:
# info about the df
chicago_public_schools_df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 69 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   School_ID                                         566 non-null    int64
 1   NAME_OF_SCHOOL                                    566 non-null    str
 2   Elementary, Middle, or High School                566 non-null    str
 3   Street_Address                                    566 non-null    str
 4   City                                              566 non-null    str
 5   State                                             566 non-null    str
 6   ZIP_Code                                          566 non-null    int64
 7   Phone_Number                                      566 non-null    str
 8   Link                                              565 non-null    str
 9   Network_Manager                                   566 non-null    str
 10  Collaborative_Name                                566 non-null    str
 11  Adequate_Yearly_Progress_Made_                    548 non-null    str
 12  Track_Schedule                                    566 non-null    str
 13  CPS_Performance_Policy_Status                     561 non-null    str
 14  CPS_Performance_Policy_Level                      561 non-null    str
 15  HEALTHY_SCHOOL_CERTIFIED                          566 non-null    str
 16  SAFETY_SCORE                                      513 non-null    float64
 17  Family_Involvement_Score                          297 non-null    float64
 18  Environment_Score                                 513 non-null    float64
 19  Instruction_Score                                 513 non-null    float64
 20  Leaders_Score                                     295 non-null    str
 21  Teachers_Score                                    295 non-null    str
 22  Parent_Engagement_Score                           432 non-null    str
 23  Parent_Environment_Score                          432 non-null    str
 24  AVERAGE_STUDENT_ATTENDANCE                        565 non-null    float64
 25  Rate_of_Misconducts__per_100_students_            566 non-null    float64
 26  Average_Teacher_Attendance                        566 non-null    float64
 27  Individualized_Education_Program_Compliance_Rate  566 non-null    float64
 28  Pk_2_Literacy__                                   403 non-null    str
 29  Pk_2_Math__                                       341 non-null    str
 30  Gr3_5_Grade_Level_Math__                          452 non-null    str
 31  Gr3_5_Grade_Level_Read__                          452 non-null    str
 32  Gr3_5_Keep_Pace_Read__                            452 non-null    str
 33  Gr3_5_Keep_Pace_Math__                            452 non-null    str
 34  Gr6_8_Grade_Level_Math__                          444 non-null    str
 35  Gr6_8_Grade_Level_Read__                          445 non-null    str
 36  Gr6_8_Keep_Pace_Math_                             444 non-null    str
 37  Gr6_8_Keep_Pace_Read__                            445 non-null    str
 38  Gr_8_Explore_Math__                               425 non-null    str
 39  Gr_8_Explore_Read__                               425 non-null    str
 40  ISAT_Exceeding_Math__                             476 non-null    float64
 41  ISAT_Exceeding_Reading__                          476 non-null    float64
 42  ISAT_Value_Add_Math                               468 non-null    float64
 43  ISAT_Value_Add_Read                               468 non-null    float64
 44  ISAT_Value_Add_Color_Math                         468 non-null    str
 45  ISAT_Value_Add_Color_Read                         468 non-null    str
 46  Students_Taking__Algebra__                        158 non-null    str
 47  Students_Passing__Algebra__                       130 non-null    str
 48  9th Grade EXPLORE (2009)                          89 non-null     str
 49  9th Grade EXPLORE (2010)                          88 non-null     str
 50  10th Grade PLAN (2009)                            82 non-null     str
 51  10th Grade PLAN (2010)                            87 non-null     str
 52  Net_Change_EXPLORE_and_PLAN                       87 non-null     str
 53  11th Grade Average ACT (2011)                     83 non-null     str
 54  Net_Change_PLAN_and_ACT                           82 non-null     str
 55  College_Eligibility__                             86 non-null     str
 56  Graduation_Rate__                                 79 non-null     str
 57  College_Enrollment_Rate__                         77 non-null     str
 58  COLLEGE_ENROLLMENT                                566 non-null    int64
 59  General_Services_Route                            566 non-null    int64
 60  Freshman_on_Track_Rate__                          87 non-null     str
 61  X_COORDINATE                                      566 non-null    float64
 62  Y_COORDINATE                                      566 non-null    float64
 63  Latitude                                          566 non-null    float64
 64  Longitude                                         566 non-null    float64
 65  COMMUNITY_AREA_NUMBER                             566 non-null    int64
 66  COMMUNITY_AREA_NAME                               566 non-null    str
 67  Ward                                              566 non-null    int64
 68  Police_District                                   566 non-null    int64
dtypes: float64(16), int64(7), str(46)
memory usage: 480.2 KB

In [335]:
# aggregate public school data
public_school_agg = chicago_public_schools_df.groupby("COMMUNITY_AREA_NUMBER").agg(
    UniqueNetworkManagersCount = ("Network_Manager", "nunique"),
    MeanSafetyScore = ("SAFETY_SCORE", "mean"),
    MeanFamilyInvolvementScore = ("Family_Involvement_Score", "mean"),
    MeanEnvironmentScore = ("Environment_Score", "mean"),
    MeanInstructionScore = ("Instruction_Score", "mean"),
    MeanStudentAttendance = ("AVERAGE_STUDENT_ATTENDANCE", "mean"),
).reset_index()

# show it
public_school_agg.head()

,COMMUNITY_AREA_NUMBER,UniqueNetworkManagersCount,MeanSafetyScore,MeanFamilyInvolvementScore,MeanEnvironmentScore,MeanInstructionScore,MeanStudentAttendance
0,1,2,43.000000,36.400000,43.250000,36.750000,93.050000
1,2,2,67.222222,59.571429,58.444444,56.555556,94.922222
2,3,2,52.000000,48.500000,59.000000,58.000000,94.542857
3,4,2,67.200000,55.000000,46.600000,44.600000,92.840000
4,5,2,85.166667,83.666667,65.500000,51.166667,95.542857

# Chicago Crime Dataframe

In [336]:
# look at the df
chicago_crime_df.head()

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,3512276,HK587712,2004-08-28,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,...,9,14.0,58.0,6,1155838.0,1873050.0,2004,41.807440,-87.703956,"(41.8074405, -87.703955849)"
1,3406613,HK456306,2004-06-26,009XX N CENTRAL PARK AVE,820,THEFT,$500 AND UNDER,OTHER,False,False,...,11,27.0,23.0,6,1152206.0,1906127.0,2004,41.898280,-87.716406,"(41.898279962, -87.716405505)"
2,8002131,HT233595,2011-04-04,043XX S WABASH AVE,820,THEFT,$500 AND UNDER,NURSING HOME/RETIREMENT HOME,False,False,...,2,3.0,38.0,6,1177436.0,1876313.0,2011,41.815933,-87.624642,"(41.815933131, -87.624642127)"
3,7903289,HT133522,2010-12-30,083XX S KINGSTON AVE,840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,4,7.0,46.0,6,1194622.0,1850125.0,2010,41.743665,-87.562463,"(41.743665322, -87.562462756)"
4,10402076,HZ138551,2016-02-02,033XX W 66TH ST,820,THEFT,$500 AND UNDER,ALLEY,False,False,...,8,15.0,66.0,6,1155240.0,1860661.0,2016,41.773455,-87.706480,"(41.773455295, -87.706480471)"

In [337]:
# shape
chicago_crime_df.shape

(533, 21)

In [338]:
# info
chicago_crime_df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 533 entries, 0 to 532
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     533 non-null    int64
 1   CASE_NUMBER            533 non-null    str
 2   DATE                   533 non-null    str
 3   BLOCK                  533 non-null    str
 4   IUCR                   533 non-null    str
 5   PRIMARY_TYPE           533 non-null    str
 6   DESCRIPTION            533 non-null    str
 7   LOCATION_DESCRIPTION   533 non-null    str
 8   ARREST                 533 non-null    bool
 9   DOMESTIC               533 non-null    bool
 10  BEAT                   533 non-null    int64
 11  DISTRICT               533 non-null    int64
 12  WARD                   490 non-null    float64
 13  COMMUNITY_AREA_NUMBER  490 non-null    float64
 14  FBICODE                533 non-null    str
 15  X_COORDINATE           529 non-null    float64
 16  Y_COORDINATE           529 non-null    float64
 17  YEAR                   533 non-null    int64
 18  LATITUDE               529 non-null    float64
 19  LONGITUDE              529 non-null    float64
 20  LOCATION               529 non-null    str
dtypes: bool(2), float64(6), int64(4), str(9)
memory usage: 136.5 KB

In [339]:
# check duplicates
chicago_crime_df.duplicated().sum()

np.int64(0)

In [340]:
# check NaN values
chicago_crime_df.isna().sum()

ID                        0
CASE_NUMBER               0
DATE                      0
BLOCK                     0
IUCR                      0
PRIMARY_TYPE              0
DESCRIPTION               0
LOCATION_DESCRIPTION      0
ARREST                    0
DOMESTIC                  0
BEAT                      0
DISTRICT                  0
WARD                     43
COMMUNITY_AREA_NUMBER    43
FBICODE                   0
X_COORDINATE              4
Y_COORDINATE              4
YEAR                      0
LATITUDE                  4
LONGITUDE                 4
LOCATION                  4
dtype: int64

In [341]:
# since some community area numbers (43) are missing, we can drop them
chicago_crime_df.dropna(subset=["COMMUNITY_AREA_NUMBER"], inplace=True)

In [342]:
# aggregate
crime_agg = chicago_crime_df.groupby("COMMUNITY_AREA_NUMBER").agg(
    TotalCrimes = ("ID", "count"),
    UniqueCrimeCategories = ("PRIMARY_TYPE", "nunique"),
    ArrestsCount = ("ARREST", "sum"),
).reset_index()

# show it
crime_agg.head()

   COMMUNITY_AREA_NUMBER  TotalCrimes  UniqueCrimeCategories  ArrestsCount
0                    1.0            6                      6             3
1                    2.0            7                      5             2
2                    3.0            4                      1             4
3                    4.0            3                      3             1
4                    5.0            4                      4             2

In [343]:
# merge all aggregated dataframes
merged = chicago_census_df.merge(
    public_school_agg, how="left", on="COMMUNITY_AREA_NUMBER"
    ).merge(crime_agg, how="left", on="COMMUNITY_AREA_NUMBER")

In [344]:
# look at the merged df
merged.head()

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX,UniqueNetworkManagersCount,MeanSafetyScore,MeanFamilyInvolvementScore,MeanEnvironmentScore,MeanInstructionScore,MeanStudentAttendance,TotalCrimes,UniqueCrimeCategories,ArrestsCount
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0,2,43.000000,36.400000,43.250000,36.750000,93.050000,6.0,6.0,3.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0,2,67.222222,59.571429,58.444444,56.555556,94.922222,7.0,5.0,2.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0,2,52.000000,48.500000,59.000000,58.000000,94.542857,4.0,1.0,4.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0,2,67.200000,55.000000,46.600000,44.600000,92.840000,3.0,3.0,1.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0,2,85.166667,83.666667,65.500000,51.166667,95.542857,4.0,4.0,2.0

In [345]:
# info about the merged df
merged.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 18 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   COMMUNITY_AREA_NUMBER                         77 non-null     float64
 1   COMMUNITY_AREA_NAME                           77 non-null     category
 2   PERCENT_OF_HOUSING_CROWDED                    77 non-null     float64
 3   PERCENT_HOUSEHOLDS_BELOW_POVERTY              77 non-null     float64
 4   PERCENT_AGED_16__UNEMPLOYED                   77 non-null     float64
 5   PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA  77 non-null     float64
 6   PERCENT_AGED_UNDER_18_OR_OVER_64              77 non-null     float64
 7   PER_CAPITA_INCOME                             77 non-null     int64
 8   HARDSHIP_INDEX                                77 non-null     float64
 9   UniqueNetworkManagersCount                    77 non-null     int64
 10  MeanSafetyScore                               76 non-null     float64
 11  MeanFamilyInvolvementScore                    70 non-null     float64
 12  MeanEnvironmentScore                          76 non-null     float64
 13  MeanInstructionScore                          76 non-null     float64
 14  MeanStudentAttendance                         77 non-null     float64
 15  TotalCrimes                                   70 non-null     float64
 16  UniqueCrimeCategories                         70 non-null     float64
 17  ArrestsCount                                  70 non-null     float64
dtypes: category(1), float64(15), int64(2)
memory usage: 11.9 KB

In [346]:
# since no crime records usually means no crimes, we can fill those features with 0
crime_cols = ["TotalCrimes", "UniqueCrimeCategories", "ArrestsCount"]
merged[crime_cols] = merged[crime_cols].fillna(0)

In [347]:
# check NaN values
merged.isna().sum()

COMMUNITY_AREA_NUMBER                           0
COMMUNITY_AREA_NAME                             0
PERCENT_OF_HOUSING_CROWDED                      0
PERCENT_HOUSEHOLDS_BELOW_POVERTY                0
PERCENT_AGED_16__UNEMPLOYED                     0
PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA    0
PERCENT_AGED_UNDER_18_OR_OVER_64                0
PER_CAPITA_INCOME                               0
HARDSHIP_INDEX                                  0
UniqueNetworkManagersCount                      0
MeanSafetyScore                                 1
MeanFamilyInvolvementScore                      7
MeanEnvironmentScore                            1
MeanInstructionScore                            1
MeanStudentAttendance                           0
TotalCrimes                                     0
UniqueCrimeCategories                           0
ArrestsCount                                    0
dtype: int64

In [348]:
# use median for quality features
quality_cols = ["MeanSafetyScore", "MeanFamilyInvolvementScore", "MeanEnvironmentScore", "MeanInstructionScore"]

for col in quality_cols:
    merged[col] = merged[col].fillna(merged[col].median())

In [349]:
# check that NaN values are 0 after merging and imputing
assert merged.isna().sum().sum() == 0

In [350]:
# check if there are duplicates
assert merged.duplicated().sum() == 0

In [351]:
# info about merged
merged.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 18 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   COMMUNITY_AREA_NUMBER                         77 non-null     float64
 1   COMMUNITY_AREA_NAME                           77 non-null     category
 2   PERCENT_OF_HOUSING_CROWDED                    77 non-null     float64
 3   PERCENT_HOUSEHOLDS_BELOW_POVERTY              77 non-null     float64
 4   PERCENT_AGED_16__UNEMPLOYED                   77 non-null     float64
 5   PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA  77 non-null     float64
 6   PERCENT_AGED_UNDER_18_OR_OVER_64              77 non-null     float64
 7   PER_CAPITA_INCOME                             77 non-null     int64
 8   HARDSHIP_INDEX                                77 non-null     float64
 9   UniqueNetworkManagersCount                    77 non-null     int64
 10  MeanSafetyScore                               77 non-null     float64
 11  MeanFamilyInvolvementScore                    77 non-null     float64
 12  MeanEnvironmentScore                          77 non-null     float64
 13  MeanInstructionScore                          77 non-null     float64
 14  MeanStudentAttendance                         77 non-null     float64
 15  TotalCrimes                                   77 non-null     float64
 16  UniqueCrimeCategories                         77 non-null     float64
 17  ArrestsCount                                  77 non-null     float64
dtypes: category(1), float64(15), int64(2)
memory usage: 11.9 KB

In [352]:
# look at the final result
merged.head()

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX,UniqueNetworkManagersCount,MeanSafetyScore,MeanFamilyInvolvementScore,MeanEnvironmentScore,MeanInstructionScore,MeanStudentAttendance,TotalCrimes,UniqueCrimeCategories,ArrestsCount
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0,2,43.000000,36.400000,43.250000,36.750000,93.050000,6.0,6.0,3.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0,2,67.222222,59.571429,58.444444,56.555556,94.922222,7.0,5.0,2.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0,2,52.000000,48.500000,59.000000,58.000000,94.542857,4.0,1.0,4.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0,2,67.200000,55.000000,46.600000,44.600000,92.840000,3.0,3.0,1.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0,2,85.166667,83.666667,65.500000,51.166667,95.542857,4.0,4.0,2.0

In [353]:
# save the merged df
merged.to_parquet("../data/processed/community_areas_agg_df.parquet", index=False)