In [1]:
import pandas as pd
from pathlib import Path
import sys
sys.path.append("../src")
from feature_engineering import convert_time_to_part_of_day, get_product_name_len

MASTER_DF_PATH = Path("../data/processed/master_df_cleaned.parquet")
master_df = pd.read_parquet(MASTER_DF_PATH)

In [2]:
# see df
master_df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle,department
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,soft drinks,beverages
1,2539329,1,prior,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,soy lactosefree,dairy eggs
2,2539329,1,prior,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,popcorn jerky,snacks
3,2539329,1,prior,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,popcorn jerky,snacks
4,2539329,1,prior,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,paper goods,household

## Creating New Features

In [3]:
# morning/afternoon/evening buy
master_df["part_of_day_purchase"] = master_df.order_hour_of_day.apply(convert_time_to_part_of_day).astype("category")

In [4]:
# product name length
master_df["product_name_length"] = master_df.product_name.apply(get_product_name_len).astype(int)

In [5]:
# days since prior order missing
master_df["days_since_prior_order_missing"] = master_df.days_since_prior_order.isna().astype(int)

In [6]:
# see final df
master_df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle,department,part_of_day_purchase,product_name_length,days_since_prior_order_missing
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,soft drinks,beverages,morning,4,1
1,2539329,1,prior,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,soy lactosefree,dairy eggs,morning,39,1
2,2539329,1,prior,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,popcorn jerky,snacks,morning,19,1
3,2539329,1,prior,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,popcorn jerky,snacks,morning,26,1
4,2539329,1,prior,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,paper goods,household,morning,32,1

In [7]:
# save the feature engineered dataframe
master_df.to_parquet("../data/processed/master_df_feature_engineered.parquet", index=False)